services:
  - type: web
    name: telegram-encryption-bot
    runtime: python
    repo: https://github.com/kingali371/tg-large-file-encrypt-bot
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
